discourse/docker_manager

- lib/docker_manager/git_repo.rb
per https://meta.discourse.org/t/docker-upgrade-links-point-only-to-the-repo-not-the-displayed-commit/20016/31?u=cpradio
This works because it is running a git command in the plugin repos folder (which it is already running to get the number of commits it is behind anyway). So this simply permits the compare link to reference the branch the discourse instance may be pointing to.
> FEATURE: Support Plugin Branches instead of assuming master

- lib/docker_manager/upgrader.rb
Overwrites local tags with those from github (useful if they've been changed on github)
From https://git-scm.com/docs/git-fetch#git-fetch---tags
```
--tags
Fetch all tags from the remote (i.e., fetch remote tags refs/tags/* into local tags 
with the same name), in addition to whatever else would otherwise be fetched.
```
See https://meta.discourse.org/t/latest-version-bug/58165
> FIX: Add --tags to git fetch in updater

- app/controllers/docker_manager/admin_controller.rb
> When using html: option, HTML entities will be escaped if the string is not marked as HTML safe by using html_safe method.
(section 2.2.7 http://guides.rubyonrails.org/layouts_and_rendering.html)
See https://meta.discourse.org/t/docker-manager-old-image-message-is-showing-raw-html/79400
> Add `html_safe` to raw HTML string

- app/controllers/docker_manager/application_controller.rb
Issue: https://meta.discourse.org/t/run-upgrade-all-from-the-command-line/109872/5
I don't have a great way to verify this change, but it matches what has been done at https://github.com/yanokwa/discourse/blob/master/app/controllers/application_controller.rb#L34.
So changes that I considered but didn't make because I wanted to make the most narrow change I understood:
* Use`unless is_api? || is_user_api?` instead of `is_api`
* Change the output to: `"[\"BAD CSRF\"]"`
> FIX: Allow requests with API keys

- manager-client/app/initializers/message-bus.js
The trailing slash was missing from the longPollingBaseUrl causing the messageBus to fail.
So I just added the trailing slash :)
> Fix message bus when using a longPollingBaseUrl

- lib/docker_manager/upgrader.rb
Flush is done via rake task.
This takes advantage of the rake task proposed here to flush the service worker cache: https://github.com/discourse/discourse/pull/8359
> FEATURE: Attempt to flush nginx service worker cache on upgrade

- lib/docker_manager/git_repo.rb
- lib/docker_manager/upgrader.rb
use rake tasks to pull compatible plugins from https://github.com/discourse/discourse/pull/9995
> Add plugin compat checkout updates

- assets/javascripts/discourse/components/upgrade-notice.js.es6
Fixes https://meta.discourse.org/t/dashboard-broken-after-2-6-0-beta1-install-removing-docker-manager-fixes-it/156963/
> FIX: Use imported getURL

- app/controllers/docker_manager/admin_controller.rb
- app/helpers/application_helper.rb
- scripts/docker_manager_upgrade.rb
Meta: https://meta.discourse.org/t/start-upgrading-button-after-successfully-upgraded/162805?u=osama
Currently when admin starts an upgrade, an HTTP request is made to the server which then forks the unicorn worker that's handling the request and perform the upgrade in the forked process. This is problematic because unicorn workers have mini racer contexts which cause problems when they're forked, and this is the cause of the reported bug. This PR amends that so we no longer fork a unicorn worker and instead spawn a fresh/standalone process to perform the upgrade. This change may make upgrades eat more memory, but we'll keep an eye on it and if it becomes a problem we'll consider a different approach.
I've tested this change on an instance running on a DO droplet and have not seen any …
> FIX: upgrade requests shouldn't timeout

- lib/docker_manager/git_repo.rb
- spec/lib/git_repo_spec.rb
This allows us to rename the main branch for plugin repos to
`origin/main` and docker_manager should continue to work.
> FEATURE: Prefer `origin/main` over `origin/master` if it exists

- lib/docker_manager/git_repo.rb
- lib/docker_manager/upgrader.rb
This involves checking out/renaming a local branch, then fetching, then
updating the upstream.
This allows plugins to automatically update to `origin/main` when
present.
> FEATURE: When upgrading, if `origin/main` exists switch to that branch

- lib/docker_manager/git_repo.rb
- lib/docker_manager/upgrader.rb
We reverted due to errors if a remote branch started with `origin/main`.
Now it will correctly identify the remote branch regardless.
> FIX: Support origin/main again

- lib/docker_manager/git_repo.rb
docker_manager must have its version checked before any other actions can be taken. Having it higher in the list makes this process much quicker for admins.
> UX: Always show the docker_manager plugin second in the list

- app/controllers/docker_manager/admin_controller.rb
- lib/docker_manager/upgrader.rb
Hi,
I added in a few lines to pass-through already set HTTP proxy environment variables.
This enabled docker_manager to perform the update for new versions of discourse and plugins on our server (which otherwise has outgoing internet blocked).  Funnily enough the check for updates was working okay (presumably this occurs with the env vars that are set in app.yml).
Hope this is good enough to incorporate or adapt.
Thanks, Ben
> allow proxy env vars

- lib/docker_manager/upgrader.rb
This is required to compile assets successfully under Ember CLI
> FIX: Run `yarn install` during updates

- app/controllers/docker_manager/admin_controller.rb
The new base image includes the following:
* Fix for CVE-2021-4034 (PwnKit) - local privilege escalation vulnerability with `pkexec`
* Ruby upgraded to 2.7.5p203
* Installing `pups` via gem
> DEV: Bump base image and expected ruby version

- manager-client/tests/helpers/start-app.js
Context: https://deprecations.emberjs.com/v4.x/#toc_ember-polyfills-deprecate-assign
> DEV: Remove use of assign polyfill

- manager-client/config/targets.js
Context: https://deprecations.emberjs.com/v3.x/#toc_3-0-browser-support-policy
> DEV: Remove ie 11 from build targets

- manager-client/app/components/progress-bar.js
Context: https://deprecations.emberjs.com/v3.x/#toc_ember-string-prototype_extensions
> DEV: Remove 'htmlSafe' string prototype extensions

- app/controllers/docker_manager/admin_controller.rb
Tell admins to rebuild their instance if the expected commit is in the working tree and they are behind it.
> FEATURE: Force a rebuild when behind a specific discourse commit.

- admin/assets/javascripts/discourse/components/docker-manager/repo-status.hbs
It doesn't support alt and the title was already a translated string.
> FIX: Incorrect use of d-icon params

- lib/docker_manager/upgrader.rb
These seem to be hurting performance in the latest version of Ruby
> FIX: Remove ruby memory flags

- .discourse-compatibility
Without this upgrades to v3.1.0.beta4+ will fail because those newer versions require Ruby 3.2 and the old, pinned docker_manager version didn't prompt for a CLI rebuild when upgrading from v3.1.0.beta1 and below.
See https://meta.discourse.org/t/runtime-error-during-upgrade-to-v3-0-3/262165
The actual fix is in 1b2d7eb0369155b6442b09adfb17b8942c04b093 which is part of the new [old-version-up-to-v3.1.0.beta1](https://github.com/discourse/docker_manager/tree/old-version-up-to-v3.1.0.beta1) branch.
> FIX: Update compatibility file for v3.1.0.beta1 and below

- lib/docker_manager/upgrader.rb
- spec/lib/git_repo_spec.rb
See https://meta.discourse.org/t/upgrade-failure-docker-manager-bug/262404
> FIX: Upgrading was broken when repo uses `master` branch

- plugin.rb
This plugin is not optional and cannot be disabled,
it's essential for self-hosting, so there is no point
showing it in the plugin list.
> FIX: Hide this plugin from the plugin list

- admin/assets/javascripts/discourse/initializers/admin-sidebar-upgrade.js
c.f. https://github.com/discourse/discourse/pull/25200
The new admin sidebar doesn't have plugin outlets, so we
need a way to register links like this Upgrade one. The
admin sidebar is currently experimental, so we need to keep
the old outlet around for now for sites who have not enabled
the admin sidebar.
> DEV: Use new JS plugin API to add admin sidebar link

- app/controllers/docker_manager/admin_controller.rb
The last forced update was more than a year ago. That old image has a lot of old dependencies, including an old `node` version which is no longer supported by some of Discourse's JS dependencies. This commit will instruct self-hosters to perform a command-line rebuild.
> Bump minimum base image version

- spec/system/admin_update_spec.rb
I'm unable to find why the tests are failing in the Discourse core repo's plugin tests workflow. These tests always pass in the plugin repo and my local dev environment.
> DEV: skip the flaky system tests

- spec/system/admin_update_spec.rb
This system spec is flaky and we are getting a blank page so I would
like to see what the HTML is. Previous printing of the page's HTML was
doing it too early such that the ember application has not even boot.
> DEV: Print page's HTML at the end after test fails

- spec/system/admin_update_spec.rb
This is still failing in our core CI. Followup to fe25a76fe3eeaa6b8500d02be32b1350791aac68
> DEV: Skip system spec

- spec/requests/admin_controller_spec.rb
Requesting /admin/docker/repos.json with a lot of plugins installed can take a lot of time because of the large number of calls to the 'git' CLI that are used to retrieve various information about the plugin (eg. branch, latest commit, remote URL, etc).
This is not a problem in production because of memoization and the much lower number of installed plugins, but it is a problem in test environment where specs requesting this page can take 10+ seconds with ~100 installed plugins.
This commit speeds up by stubbing the `find_all` method to return only the first few repositories.
> DEV: Speed up /admin/docker/repos.json spec

- spec/lib/git_repo_spec.rb
- spec/support/git_helpers.rb
Git repositories will be initialized less often and then copied for each
spec. This reduces the calls to 'git' and the total execution time of
the specs.
> DEV: Optimize specs

- .discourse-compatibility
This pin means that sites will not show an update available for docker_manager, and will then hit a pnpm/yarn error when updating core.
docker_manager is compatible with the 3.3.x series, so we can remove this pin.
> FIX: Remove <3.4.0.beta1 version pin

- admin/assets/javascripts/discourse/components/repo-status.gjs
- assets/stylesheets/common/docker-manager.scss
* Follow up to some class name changes in https://github.com/discourse/discourse/pull/29360
* Alignment tweak to the status label
> DEV: update the classname to match in core; success label tweak

- lib/docker_manager/upgrader.rb
The upgrade process was triggering the database migrations, and then calling `User.find()`. This is problematic because the `users` table may have been changed by the migrations, and accessing it with the 'old code' will raise an exception.
This commit tweaks the Upgrader so that it loads the user object into memory **before** running database migrations.
> FIX: Minimize database access following `db:migrate`

- .discourse-compatibility
- admin/assets/javascripts/discourse/components/repo-status.gjs
This PR updates deprecated Font Awesome icon names. For more detail, refer to the announcement at https://meta.discourse.org/t/-/325349.
> DEV: Update deprecated Font Awesome icon names

- assets/stylesheets/common/docker-manager.scss
Removed the hardcoded padding and hex value for the `--success-low` variable
Related: moved the badge styling to core: https://github.com/discourse/discourse/pull/30125
> UX: Badge styling tweaks

- admin/assets/javascripts/discourse/templates/update.hbs
This PR updates more deprecated Font Awesome icon names. For more detail, refer to the announcement at https://meta.discourse.org/t/-/325349.
> DEV: Update more deprecated Font Awesome icon names

- admin/assets/javascripts/discourse/templates/update-index.hbs
- admin/assets/javascripts/discourse/templates/update-show.hbs
- admin/assets/javascripts/discourse/templates/update.hbs
- config/locales/client.en.yml
- test/javascripts/acceptance/docker-manager-test.js
This PR updates the header of the admin page to be more consistent with the rest of the admin UI.
The tabs to access the different sub-pages have also been updated.
> UX: Update the admin page header to use `DPageHeader`

- admin/assets/javascripts/discourse/templates/update-index.hbs
The message that tells the users how to upgrade shows a redundant `git pull` that is not needed anymore.
> UX: Removed a redundant git pull statement from the user message

- spec/system/core_features_spec.rb
The shared example is not available in stable yet and is causing the builds for the stable branch in `discourse/discourse` to fail since this is an official plugin.
> DEV: Skip core features specs on stable

- .github/workflows/discourse-plugin.yml
- spec/system/core_features_spec.rb
This plugin is important so we want to ensure that the tests pass
against the `stable` branch too.
> DEV: Add `ci-stable` job

- spec/system/core_features_spec.rb
Now that `stable` provides the smoke specs, we can enable them again for this plugin.
> DEV: Enable smoke specs again
